[package]
name = "astro-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Astronomy utils"
repository = "https://github.com/eta077/astro-rs"
readme = "README.md"
keywords = ["astronomy", "astrophysics", "fits", "utility"]
categories = ["aerospace", "data-structures", "parser-implementations", "science"]

exclude = [
    ".github",
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
chrono = { version = "0.4", optional = true }
hyper = { version = "0.14", features = ["client", "http1", "tcp"], optional = true }
measurements = { version = "0.11", optional = true }
thiserror = { version = "1.0" }
urlencoding = { version = "2.1", optional = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
image = { version = "0.24", default-features = false, features = ["jpeg"] }
tokio-test = { version = "0.4" }

[features]
default = ["fits"]
coordinates = ["dep:chrono", "dep:hyper", "dep:measurements", "dep:urlencoding"]
cosmology = []
fits = []

[[bench]]
name = "fits_benchmark"
harness = false

[profile.bench]
debug = true
