[package]
name = "astro-rs"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Astronomy utils"
repository = "https://github.com/eta077/astro-rs"
readme = "README.md"
keywords = ["astronomy", "astrophysics", "fits", "utility"]
categories = ["aerospace", "data-structures", "parser-implementations", "science"]

exclude = [
    ".github",
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
hifitime = { version = "3.6", optional = true }
hyper = { version = "0.14", features = ["client", "http1", "tcp"], optional = true }
once_cell = { version = "1.16", optional = true }
regex = { version = "1.7", optional = true }
rust_decimal = { version = "1.29" }
thiserror = { version = "1.0.7" }
uom = { version = "0.35", optional = true, default-features = false, features = ["autoconvert", "si", "std", "f64"] }
urlencoding = { version = "2.1", optional = true }

# pin to retain MSRV
tokio = { version = "1, <1.30.0" }
memchr = { version = "2.4, <2.6.3" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
image = { version = "0.24", default-features = false, features = ["jpeg"] }
tokio-test = { version = "0.4" }

[features]
default = ["coordinates", "fits"]
coordinates = ["dep:hifitime", "dep:hyper", "dep:once_cell", "dep:regex", "dep:uom", "dep:urlencoding"]
cosmology = []
fits = []

[[bench]]
name = "fits_benchmark"
harness = false

[profile.bench]
debug = true
