[package]
name = "astro-rs"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Astronomy utils"
repository = "https://github.com/eta077/astro-rs"
readme = "README.md"

exclude = [
    ".github",
    "assets",
    "benches",
    "tests" 
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4" }
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
measurements = { version = "0.11" }
thiserror = { version = "1.0" }
urlencoding = { version = "2.1" }

[dev-dependencies]
criterion = "0.3"
tokio-test = { version = "0.4" }

[lib]
bench = false

[[bench]]
name = "fits_benchmark"
harness = false
