[package]
name = "astro-rs"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Astronomy utils"
repository = "https://github.com/eta077/astro-rs"
readme = "README.md"

exclude = [
    ".github",
    "tests" 
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measurements = { version = "0.11" }
thiserror = { version = "1.0" }
