codecov:
  require_ci_to_pass: true
  
comment:
  behavior: default
  layout: "reach,diff,files"
  
coverage:
  status:
    changes: false
    patch: false
    project: false
    
ignore:
  - "tests"

github_checks:
  annotations: true
