on:
  pull_request:
    branches:
      - main

name: Bench

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: boa-dev/criterion-compare-action@v3.2.0
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}