on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Bench

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo bench

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ github.sha }}_bench
          path: ./target/criterion