on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

name: Test

jobs:
  test:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v1

      - name: Download grcov
        run: |
          cargo install grcov
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Run coverage
        run: |
          rm -rf coverage
          mkdir coverage
          CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" -o coverage/tests.lcov
          rm -rf *.profraw
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: coverage/*.lcov
          fail_ci_if_error: true
